default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  # username: gauchada
  # password: gauchada

development:
  <<: *default
  database: application_development

test:
  <<: *default
  database: application_test

production:
  <<: *default
  database: application_production
